GET http://localhost:8080/api/messages

###
POST http://localhost:8080/api/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKb3Rhcm8iLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiZXhwIjoxNTg4Nzg0NzI1fQ.4lTfWFAzAmYBIan4OvgOIj7TEM-KesS9C7czIbf9za8
Content-Type: application/json

{"texte": "Messaje"}

###
POST http://localhost:8080/api/messages
Authorization: Basic admin admin
Content-Type: application/json

{"texte": "Msg admin"}

###
GET http://localhost:8080/api/messages/2

###
DELETE http://localhost:8080/api/messages/1
Authorization: Basic Jotaro Dolphin

###
POST http://localhost:8080/api/utilisateurs
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iLCJST0xFX1VTRVIiXSwiZXhwIjoxNTg4Nzg0ODQwfQ.MTm9yGRQQRmcW7DHCDN5TJy6D3D_w6dAypbU3XqSOaY
Content-Type: application/json

{ "login": "yohan", "password": "yohan", "isAdmin": true }

###
GET http://localhost:8080/api/utilisateurs/Jotaro
Authorization: Basic admin admin

###
POST http://localhost:8080/api/login?username=Jotaro&password=Dolphin

###
POST http://localhost:8080/api/login?username=admin&password=admin

###